### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by ViBiOh** [KtourzaJeremy/TTP#2]
La documentation est un fichier vide sur la branche TTP-C#. J'en vois sur la branche, quel fichier dois-je regarder ?

**Comment by alexisjaubourg** [comment]
Bonjour,

Notre documentation du projet est le fichier "Rapport TTP Final.md". Désolé
du manque de clarté.

Bonne journée,

Alexis Jaubourg

2017-02-22 21:10 GMT+01:00 Vincent <notifications@github.com>:
